CREATE TABLE Jogos (
                       JogoID SERIAL PRIMARY KEY,
                       Titulo VARCHAR(255) NOT NULL,
                       Genero VARCHAR(100) NOT NULL,
                       Plataforma VARCHAR(100) NOT NULL,
                       FaixaEtaria VARCHAR(50) NOT NULL,
                       Multiplayer VARCHAR(10) NOT NULL,
                       AnoLancamento INT NOT NULL,
                       Avaliacao FLOAT NOT NULL,
                       EstiloVisual VARCHAR(100) NOT NULL,
                       Desenvolvedora VARCHAR(100) NOT NULL,
                       DuracaoHoras INT NOT NULL
);

INSERT INTO Jogos (Titulo, Genero, Plataforma, FaixaEtaria, Multiplayer, AnoLancamento, Avaliacao, EstiloVisual, Desenvolvedora, DuracaoHoras) VALUES
                                                                                                                                                   ('The Legend of Zelda: Breath of the Wild', 'Ação/Aventura', 'Nintendo Switch', '12+', 'Não', 2017, 9.7, '3D', 'Nintendo', 50),
                                                                                                                                                   ('God of War', 'Ação', 'PS4', '18+', 'Não', 2018, 9.6, '3D', 'Santa Monica Studio', 30),
                                                                                                                                                   ('Hollow Knight', 'Metroidvania', 'PC', '10+', 'Não', 2017, 9.0, '2D', 'Team Cherry', 25),
                                                                                                                                                   ('Stardew Valley', 'Simulação', 'PC', 'Livre', 'Sim', 2016, 8.8, 'Pixel Art', 'ConcernedApe', 80),
                                                                                                                                                   ('FIFA 23', 'Esporte', 'Multiplataforma', 'Livre', 'Sim', 2022, 7.5, '3D', 'EA Sports', 999),
                                                                                                                                                   ('Elden Ring', 'RPG', 'Multiplataforma', '16+', 'Sim', 2022, 9.5, '3D', 'FromSoftware', 60),
                                                                                                                                                   ('Minecraft', 'Sandbox', 'Multiplataforma', 'Livre', 'Sim', 2011, 9.0, 'Pixel Art', 'Mojang', 999),
                                                                                                                                                   ('Overcooked 2', 'Party Game', 'PC', 'Livre', 'Sim', 2018, 8.0, '2D', 'Ghost Town Games', 10),
                                                                                                                                                   ('Among Us', 'Party Game', 'Mobile', 'Livre', 'Sim', 2018, 7.0, '2D', 'Innersloth', 5),
                                                                                                                                                   ('The Witcher 3: Wild Hunt', 'RPG', 'Multiplataforma', '18+', 'Não', 2015, 9.8, '3D', 'CD Projekt', 70),
                                                                                                                                                   ('Celeste', 'Plataforma', 'PC', '10+', 'Não', 2018, 8.9, 'Pixel Art', 'Matt Makes Games', 10),
                                                                                                                                                   ('Red Dead Redemption 2', 'Ação/Aventura', 'Multiplataforma', '18+', 'Não', 2018, 9.7, '3D', 'Rockstar Games', 80),
                                                                                                                                                   ('Dark Souls III', 'RPG', 'Multiplataforma', '16+', 'Não', 2016, 9.2, '3D', 'FromSoftware', 50),
                                                                                                                                                   ('Animal Crossing: New Horizons', 'Simulação', 'Nintendo Switch', 'Livre', 'Sim', 2020, 9.1, '3D', 'Nintendo', 200),
                                                                                                                                                   ('Hades', 'Roguelike', 'PC', '16+', 'Não', 2020, 9.0, '2D', 'Supergiant Games', 25),
                                                                                                                                                   ('Portal 2', 'Puzzle', 'PC', '12+', 'Sim', 2011, 9.5, '3D', 'Valve', 10),
                                                                                                                                                   ('Undertale', 'RPG', 'PC', 'Livre', 'Não', 2015, 9.0, 'Pixel Art', 'Toby Fox', 8),
                                                                                                                                                   ('Cuphead', 'Plataforma', 'PC', 'Livre', 'Sim', 2017, 8.5, 'Desenho Animado', 'Studio MDHR', 12),
                                                                                                                                                   ('League of Legends', 'MOBA', 'PC', '12+', 'Sim', 2009, 8.2, '3D', 'Riot Games', 999),
                                                                                                                                                   ('Valorant', 'FPS', 'PC', '16+', 'Sim', 2020, 8.5, '3D', 'Riot Games', 999),
                                                                                                                                                   ('Cyberpunk 2077', 'RPG', 'Multiplataforma', '18+', 'Não', 2020, 7.8, '3D', 'CD Projekt', 60),
                                                                                                                                                   ('Genshin Impact', 'RPG', 'Multiplataforma', '12+', 'Sim', 2020, 8.1, '3D', 'miHoYo', 999),
                                                                                                                                                   ('Fortnite', 'Battle Royale', 'Multiplataforma', '12+', 'Sim', 2017, 8.0, '3D', 'Epic Games', 999),
                                                                                                                                                   ('Call of Duty: Modern Warfare', 'FPS', 'Multiplataforma', '18+', 'Sim', 2019, 8.3, '3D', 'Infinity Ward', 30),
                                                                                                                                                   ('It Takes Two', 'Co-op Aventura', 'Multiplataforma', '12+', 'Sim', 2021, 9.0, '3D', 'Hazelight Studios', 15),
                                                                                                                                                   ('Dead Cells', 'Roguelike', 'PC', '12+', 'Não', 2018, 8.9, 'Pixel Art', 'Motion Twin', 20),
                                                                                                                                                   ('Ori and the Blind Forest', 'Plataforma', 'PC', '10+', 'Não', 2015, 9.1, '2D', 'Moon Studios', 8),
                                                                                                                                                   ('Forza Horizon 5', 'Corrida', 'Xbox', 'Livre', 'Sim', 2021, 9.0, '3D', 'Playground Games', 100),
                                                                                                                                                   ('Rocket League', 'Esporte', 'Multiplataforma', 'Livre', 'Sim', 2015, 8.6, '3D', 'Psyonix', 999),
                                                                                                                                                   ('Slay the Spire', 'Card Game', 'PC', 'Livre', 'Não', 2019, 8.7, '2D', 'MegaCrit', 25),
                                                                                                                                                   ('Terraria', 'Sandbox', 'Multiplataforma', 'Livre', 'Sim', 2011, 9.0, 'Pixel Art', 'Re-Logic', 999),
                                                                                                                                                   ('Bioshock Infinite', 'FPS', 'Multiplataforma', '18+', 'Não', 2013, 9.3, '3D', 'Irrational Games', 12),
                                                                                                                                                   ('Fall Guys', 'Party Game', 'Multiplataforma', 'Livre', 'Sim', 2020, 7.5, '3D', 'Mediatonic', 999),
                                                                                                                                                   ('Dishonored 2', 'Stealth', 'Multiplataforma', '16+', 'Não', 2016, 8.6, '3D', 'Arkane Studios', 20),
                                                                                                                                                   ('Inside', 'Puzzle', 'PC', '12+', 'Não', 2016, 8.9, '2.5D', 'Playdead', 5),
                                                                                                                                                   ('Little Nightmares', 'Terror', 'Multiplataforma', '12+', 'Não', 2017, 8.0, '2.5D', 'Tarsier Studios', 6),
                                                                                                                                                   ('Mass Effect 2', 'RPG', 'PC', '18+', 'Não', 2010, 9.2, '3D', 'BioWare', 35),
                                                                                                                                                   ('Super Mario Odyssey', 'Plataforma', 'Nintendo Switch', 'Livre', 'Não', 2017, 9.6, '3D', 'Nintendo', 15),
                                                                                                                                                   ('Firewatch', 'Narrativo', 'PC', '16+', 'Não', 2016, 8.4, '3D', 'Campo Santo', 5),
                                                                                                                                                   ('The Forest', 'Survival', 'PC', '18+', 'Sim', 2018, 8.3, '3D', 'Endnight Games', 40),
                                                                                                                                                   ('Subnautica', 'Survival', 'PC', '12+', 'Não', 2018, 8.9, '3D', 'Unknown Worlds', 35),
                                                                                                                                                   ('The Sims 4', 'Simulação', 'PC', 'Livre', 'Sim', 2014, 8.0, '3D', 'Maxis', 999),
                                                                                                                                                   ('No Man’s Sky', 'Exploração', 'Multiplataforma', '12+', 'Sim', 2016, 7.5, '3D', 'Hello Games', 999),
                                                                                                                                                   ('Battlefield V', 'FPS', 'Multiplataforma', '18+', 'Sim', 2018, 7.9, '3D', 'DICE', 50),
                                                                                                                                                   ('Apex Legends', 'Battle Royale', 'Multiplataforma', '14+', 'Sim', 2019, 8.4, '3D', 'Respawn Entertainment', 999),
                                                                                                                                                   ('Doom Eternal', 'FPS', 'Multiplataforma', '18+', 'Não', 2020, 9.1, '3D', 'id Software', 20),
                                                                                                                                                   ('Monster Hunter: World', 'RPG', 'Multiplataforma', '12+', 'Sim', 2018, 8.8, '3D', 'Capcom', 80),
                                                                                                                                                   ('Resident Evil Village', 'Terror', 'Multiplataforma', '18+', 'Não', 2021, 8.5, '3D', 'Capcom', 10),
                                                                                                                                                   ('Horizon Zero Dawn', 'Ação', 'Multiplataforma', '16+', 'Não', 2017, 9.0, '3D', 'Guerrilla Games', 45),
                                                                                                                                                   ('Persona 5', 'RPG', 'PS4', '16+', 'Não', 2016, 9.5, '2D/3D', 'Atlus', 90),
                                                                                                                                                   ('Ghost of Tsushima', 'Ação', 'PS4', '18+', 'Sim', 2020, 9.3, '3D', 'Sucker Punch', 40);

